import { EffectRegistry } from '../effects/core/EffectRegistry';
import { numberParameter as n, seedParameter, shaderEffect } from '../effects/core/shader';
import type { EffectDefinition } from '../effects/core/types';
import { fbmNoise } from '../effects/generative/fbmNoise';
import { voronoiField } from '../effects/generative/voronoiField';
import { interference } from '../effects/generative/interference';
import { radialField } from '../effects/generative/radialField';
import { interferenceFieldGLSL, radialFieldGLSL } from '../effects/generative/analyticFields';
const tones = [n('foreground', 'Foreground gray', 1, 0, 1), n('background', 'Background gray', 0, 0, 1)];
const noise = shaderEffect({ id: 'noise', name: 'Noise', category: 'Generators', description: 'Seedovaný nezávislý šum v každém pixelu.', parameters: [seedParameter], body: 'float value = hash(vec3(floor(uv * uSize), p_seed)); finalColor = vec4(vec3(value), 1.0);' });
const checker = shaderEffect({ id: 'checker', name: 'Checker', category: 'Generators', description: 'Šachovnice s velikostí buněk v pixelech.', parameters: [n('cellSize', 'Cell size / px', 32, 1, 512, 1), ...tones], body: 'vec2 cell = floor(uv * uSize / p_cellSize); float value = mod(cell.x + cell.y, 2.0); finalColor = vec4(vec3(mix(p_background, p_foreground, value)), 1.0);' });
const lines = shaderEffect({ id: 'lines', name: 'Lines', category: 'Generators', description: 'Natočené pravidelné pruhy.', parameters: [n('spacing', 'Spacing / px', 24, 2, 512, 1), n('width', 'Line width', 0.35, 0, 1), n('angle', 'Angle', 30, -180, 180, 1), ...tones], body: 'vec2 point = (uv - 0.5) * uSize; float angle = radians(p_angle); float phase = fract(dot(point, vec2(cos(angle), sin(angle))) / p_spacing); float value = 1.0 - step(p_width, phase); finalColor = vec4(vec3(mix(p_background, p_foreground, value)), 1.0);' });
const dots = shaderEffect({ id: 'dots', name: 'Dots', category: 'Generators', description: 'Pravidelná síť kruhových bodů.', parameters: [n('spacing', 'Spacing / px', 24, 2, 512, 1), n('radius', 'Dot radius', 0.3, 0, 0.5), ...tones], body: 'vec2 point = fract(uv * uSize / p_spacing) - 0.5; float value = 1.0 - smoothstep(p_radius - 0.5 / p_spacing, p_radius + 0.5 / p_spacing, length(point)); finalColor = vec4(vec3(mix(p_background, p_foreground, value)), 1.0);' });
function field(id: string, name: string, effect: EffectDefinition): EffectDefinition { return { ...effect, id, name, category: 'Generators', inputs: [], description: `Procedurální zdroj: ${name}. Nevyžaduje bitmapu.`, parameters: effect.parameters.filter(parameter => parameter.id !== 'amount'), createRenderer(context) { const runtime = effect.createRenderer(context); return { get filter() { return runtime.filter!; }, update(parameters, next) { runtime.update({ ...parameters, amount: 1 }, next); }, destroy() { runtime.destroy(); } }; } }; }
export const generatorRegistry = new EffectRegistry();
const interferenceGenerator = shaderEffect({ id: 'interference', name: 'Interference', category: 'Generators', description: 'Procedurální interference natočených vln.', parameters: interference.parameters.filter(parameter => parameter.id !== 'amount'), helpers: interferenceFieldGLSL, body: 'float value = interferenceField((uv - 0.5) * uSize / min(uSize.x, uSize.y), p_waveCount, p_frequency, p_angle, p_phase); finalColor = vec4(vec3(value), 1.0);' });
const radialGenerator = shaderEffect({ id: 'radial', name: 'Radial Field', category: 'Generators', description: 'Koncentrické kruhy a spirály s útlumem.', parameters: radialField.parameters.filter(parameter => parameter.id !== 'amount'), helpers: radialFieldGLSL, body: 'float value = radialFieldValue((uv - vec2(p_centerX, p_centerY)) * uSize / min(uSize.x, uSize.y), p_frequency, p_twist, p_falloff); finalColor = vec4(vec3(value), 1.0);' });
for (const definition of [noise, checker, lines, dots, field('fbm', 'FBM Noise', fbmNoise), field('voronoi', 'Voronoi', voronoiField), interferenceGenerator, radialGenerator]) generatorRegistry.register(definition);
